# _config.yml

title: CRUD TODO WEB APP
description: A brief description of my site
url: "https://rlmgtr.github.io"  # Replace with your username
baseurl: "/MERN-CRUD-todo"  # Replace with your repo name
theme: jekyll-theme-primer

plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-relative-links